# Generated by Django 4.0.3 on 2022-03-30 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitymap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Locations',
        ),
    ]
