# Generated by Django 4.0.3 on 2022-04-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitymap', '0002_rename_store_locations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
