# Generated by Django 4.0.3 on 2022-04-15 09:05

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('charitymap', '0003_rename_locations_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
                ('votes', models.IntegerField()),
                ('type', models.CharField(choices=[('1', 'Store'), ('2', 'Bin')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='VotedLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
    ]
